# Generated by Django 6.0 on 2026-01-05 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='linenox',
            new_name='linenos',
        ),
    ]
